In [1]:
import os
import sys
import pandas as pd
from tqdm.notebook import tqdm

from utilities import get_date, walk_through_files, get_subzone_name_from_dir

pd.set_option('display.max_rows', 500)

In [2]:
RECORDS_PATH =  os.path.join('..', 'raw-files', 'sg_subzones_devices')
SAVEPATH = os.path.join('intermediate-files', 'devicecount-subzone-day.csv')

In [3]:
ix = 0
dict_placeholder = {}


for filepath in tqdm(walk_through_files(RECORDS_PATH, 'csv.gz', fullpath=True)):
    
    # parse file name to get date and loc 
    try:
        subzone = get_subzone_name_from_dir(filepath)
        date = get_date(filepath)
    except ValueError:
        print(filename)
    
    # read into df
    _df = pd.read_csv(filepath, compression='gzip', 
                      names=['id', 'os'], 
                      dtype={'id': 'object', 'os': 'int8'})
    
    android_count = len(_df[_df['os']==0])
    ios_count = len(_df[_df['os']==1])
    
    # init list and add to dict
    dict_placeholder[ix] = [subzone, date, android_count, ios_count]
    
    ix += 1

0it [00:00, ?it/s]

In [4]:
df = (pd.DataFrame.from_dict(dict_placeholder, orient='index',
                             columns=['subzone', 'date', 'android_count', 'ios_count'])
      .astype({'subzone': 'object', 
               'date': 'datetime64',
               'android_count': 'int', 
               'ios_count': 'int'})
      .sort_values(['date', 'subzone'], ignore_index=True)
     )

In [5]:
df.head(10)

                   subzone       date  android_count  ios_count
0                admiralty 2020-01-01             63         10
1             airport road 2020-01-01             54          3
2           alexandra hill 2020-01-01           1080        203
3          alexandra north 2020-01-01            362         74
4                 aljunied 2020-01-01           5687       1033
5               anak bukit 2020-01-01           1296        310
6               anchorvale 2020-01-01           1894        380
7   ang mo kio town centre 2020-01-01           1200        176
8                    anson 2020-01-01            265         77
9                balestier 2020-01-01           3543       1289

In [6]:
df[df['android_count']<df['ios_count']]

                            subzone       date  android_count  ios_count
21                        boat quay 2020-01-01            987       1060
195             pulau punggol barat 2020-01-01              0          1
1217                      boat quay 2020-01-05            811       1009
1516                      boat quay 2020-01-06            988       1204
1815                      boat quay 2020-01-07           1160       1229
2414                      boat quay 2020-01-09           1225       1766
2588            pulau punggol barat 2020-01-09              0          1
2714                      boat quay 2020-01-10           1282       1321
3013                      boat quay 2020-01-11           1108       1503
3312                      boat quay 2020-01-12            878       1180
4383            pulau punggol barat 2020-01-15              0          1
7972            pulau punggol barat 2020-01-27              0          1
7973            pulau punggol timor 2020-01-27              0          1
8273            pulau punggol timor 2020-01-28              0          1
8463                 greenwood park 2020-01-29             30         56
8762                 greenwood park 2020-01-30             34         46
9070                   holland road 2020-01-31           1666       1763
10793                     boat quay 2020-02-06            848       1209
12588                     boat quay 2020-02-12           1186       1670
12887                     boat quay 2020-02-13           1479       2180
13784                     boat quay 2020-02-16           1454       1564
13864                 istana negara 2020-02-16           1155       1251
14163                 istana negara 2020-02-17           1253       1310
14462                 istana negara 2020-02-18           1252       1333
14664               alexandra north 2020-02-19            220        236
14666                    anak bukit 2020-02-19           1237       1322
14690                         bugis 2020-02-19            405        416
14714              clementi central 2020-02-19            733        903
14727                   dhoby ghaut 2020-02-19            246        257
14729                       dunearn 2020-02-19            230        290
14734                  farrer court 2020-02-19            213        238
14746                greenwood park 2020-02-19              8         17
14752                      hillview 2020-02-19            442        538
14754                  holland road 2020-02-19            586        764
14757               hougang central 2020-02-19            403        430
14762                 istana negara 2020-02-19            578        824
14779                        katong 2020-02-19            442        476
14810                margaret drive 2020-02-19            490        500
14815                 marine parade 2020-02-19            887        981
14816                     marymount 2020-02-19            887        890
14819                      mei chin 2020-02-19            542        544
14830                 newton circus 2020-02-19            140        230
14837               pasir panjang 1 2020-02-19            267        288
14842                pasir ris west 2020-02-19            697        703
14843                      paterson 2020-02-19            138        159
14858           punggol town centre 2020-02-19            140        143
14865                robertson quay 2020-02-19            334        390
14880                       sennett 2020-02-19            414        415
14894                      somerset 2020-02-19            844       1132
14951            yio chu kang north 2020-02-19             88         89
15061                 istana negara 2020-02-20            968       1059
15280                     boat quay 2020-02-21            678       1212
15360                 istana negara 2020-02-21            944       1113
15579                     boat quay 2020-02-22            677       1342
15659                 istana negara 2020-02-22           1034       1230
15791                      somerset 2020-02-22           1349       1580
15878                     boat quay 2020-02-23            670       1546
15958                 istana negara 2020-02-23            944       1158
16039                      paterson 2020-02-23            144        151
16052           pulau punggol barat 2020-02-23              0          1
16091                      somerset 2020-02-23           1284       1625
16159               alexandra north 2020-02-24            231        234
16161                    anak bukit 2020-02-24           1349       1392
16177                     boat quay 2020-02-24            701       1662
16209              clementi central 2020-02-24            826        978
16223                         dover 2020-02-24            432        450
16229                  farrer court 2020-02-24            235        261
16241                greenwood park 2020-02-24             14         23
16247                      hillview 2020-02-24            452        547
16249                  holland road 2020-02-24            885       1097
16257                 istana negara 2020-02-24            961       1055
16311                     marymount 2020-02-24            929        971
16325                 newton circus 2020-02-24            175        239
16337                pasir ris west 2020-02-24            681        730
16352                 punggol field 2020-02-24            951       1079
16372          sengkang town centre 2020-02-24           1513       1514
16389                      somerset 2020-02-24           1304       1371
16409             telok blangah way 2020-02-24            363        379
16413           tiong bahru station 2020-02-24            564        608
16418                    townsville 2020-02-24            520        561
16457                alexandra hill 2020-02-25            395        411
16458               alexandra north 2020-02-25            140        173
16460                    anak bukit 2020-02-25            753        862
16463                         anson 2020-02-25            116        141
16465                       bangkit 2020-02-25            282        308
16469               bedok reservoir 2020-02-25            427        444
16472                     bendemeer 2020-02-25            782        803
16476                     boat quay 2020-02-25            512       1136
16479                     boon teck 2020-02-25            226        313
16485           bukit batok central 2020-02-25            401        427
16486              bukit batok east 2020-02-25            244        265
16488              bukit batok west 2020-02-25            257        291
16498                     cheng san 2020-02-25            469        517
16505                     city hall 2020-02-25           7438       7786
16508              clementi central 2020-02-25            423        624
16511                clementi woods 2020-02-25            275        328
16513                  commonwealth 2020-02-25            113        128
16520                    depot road 2020-02-25            184        191
16521                   dhoby ghaut 2020-02-25            181        186
16528                  farrer court 2020-02-25            155        171
16533                       frankel 2020-02-25            845        903
16537                      ghim moh 2020-02-25            168        227
16540                greenwood park 2020-02-25              5          7
16541                        guilin 2020-02-25            289        314
16544                henderson hill 2020-02-25            331        408
16546                      hillview 2020-02-25            251        399
16547                 holland drive 2020-02-25            215        254
16548                  holland road 2020-02-25            431        514
16551               hougang central 2020-02-25            228        240
16552                  hougang east 2020-02-25            346        379
16553                  hougang west 2020-02-25            801        806
16556                 istana negara 2020-02-25            444        583
16572                       kangkar 2020-02-25            515        533
16573                        katong 2020-02-25            330        371
16581                         kovan 2020-02-25           2746       2832
16590            lorong 8 toa payoh 2020-02-25            160        181
16604                margaret drive 2020-02-25            316        367
16606                   marina east 2020-02-25             45         54
16609                 marine parade 2020-02-25            581        702
16610                     marymount 2020-02-25            477        663
16613                      mei chin 2020-02-25            359        425
16624                 newton circus 2020-02-25            104        157
16631               pasir panjang 1 2020-02-25            199        224
16634               pasir ris drive 2020-02-25            854        892
16636                pasir ris west 2020-02-25            453        455
16637                      paterson 2020-02-25             84        100
16641                      pei chun 2020-02-25            138        140
16650                 punggol canal 2020-02-25             13         19
16651                 punggol field 2020-02-25            586        729
16655                       redhill 2020-02-25            268        281
16671          sengkang town centre 2020-02-25            837       1007
16678               serangoon north 2020-02-25            381        463
16682                        siglap 2020-02-25            187        230
16685                 simpang south 2020-02-25             23         26
16688                      somerset 2020-02-25            626        739
16699                 tampines west 2020-02-25           1249       1270
16701                  tanglin halt 2020-02-25            225        259
16707            telok blangah rise 2020-02-25            215        252
16708             telok blangah way 2020-02-25            192        259
16711                   tiong bahru 2020-02-25            595        703
16712           tiong bahru station 2020-02-25            316        442
16715                      toh guan 2020-02-25            296        344
16717                    townsville 2020-02-25            285        411
16718                     trafalgar 2020-02-25            717        868
16751                    yuhua east 2020-02-25            395        457
16752                    yuhua west 2020-02-25            281        339
16775                     boat quay 2020-02-26           1265       1333
16804                     city hall 2020-02-26           4346       5193
16855                 istana negara 2020-02-26            202        310
17056               alexandra north 2020-02-27             48         53
17059                    anchorvale 2020-02-27            246        262
17063                       bangkit 2020-02-27            124        133
17064              bayfront subzone 2020-02-27             58         67
17067               bedok reservoir 2020-02-27            178        186
17068                   bedok south 2020-02-27            245        255
17086              bukit batok west 2020-02-27            117        120
17106              clementi central 2020-02-27            169        196
17108                 clementi west 2020-02-27            104        115
17110                 clifford pier 2020-02-27             43         72
17126                  farrer court 2020-02-27             44         71
17128                      fernvale 2020-02-27            274        302
17138                greenwood park 2020-02-27              0          3
17144                      hillview 2020-02-27            106        152
17145                 holland drive 2020-02-27             78         83
17150                  hougang east 2020-02-27            160        172
17154                 istana negara 2020-02-27            198        292
17170                       kangkar 2020-02-27            193        229
17179                         kovan 2020-02-27           1384       1422
17198                       malcolm 2020-02-27             38         43
17200                 mandai estate 2020-02-27              4         19
17207                 marine parade 2020-02-27            219        254
17209                       matilda 2020-02-27            179        275
17232               pasir ris drive 2020-02-27            391        394
17234                pasir ris west 2020-02-27            182        224
17248                 punggol canal 2020-02-27              3         18
17249                 punggol field 2020-02-27            241        349
17250           punggol town centre 2020-02-27             31         32
17256                     rivervale 2020-02-27            410        440
17266                sembawang east 2020-02-27              2          4
17269          sengkang town centre 2020-02-27            350        614
17276               serangoon north 2020-02-27            181        190
17280                        siglap 2020-02-27             55         60
17286                      somerset 2020-02-27            285        332
17305            telok blangah rise 2020-02-27             91        102
17309                   tiong bahru 2020-02-27            247        328
17310           tiong bahru station 2020-02-27            126        137
17313                      toh guan 2020-02-27            122        128
17315                    townsville 2020-02-27            134        138
17316                     trafalgar 2020-02-27            352        410
17324                    ulu pandan 2020-02-27             69         72
17348                    yuhua east 2020-02-27            166        199
17349                    yuhua west 2020-02-27            126        140
17353                alexandra hill 2020-02-28            536        594
17356                    anak bukit 2020-02-28            817        861
17359                         anson 2020-02-28            175        213
17372                     boat quay 2020-02-28            632       1713
17376                     boulevard 2020-02-28            545        678
17378                    bras basah 2020-02-28            223        249
17380                         bugis 2020-02-28            479        533
17388                         cecil 2020-02-28            398        603
17401                     city hall 2020-02-28           4182       5907
17403                   clarke quay 2020-02-28            177        178
17404              clementi central 2020-02-28            572        600
17407                clementi woods 2020-02-28            339        343
17408                 clifford pier 2020-02-28            452        500
17417                   dhoby ghaut 2020-02-28            244        321
17418                         dover 2020-02-28            331        349
17436                greenwood park 2020-02-28              4         10
17442                      hillview 2020-02-28            290        295
17444                  holland road 2020-02-28            401        528
17447               hougang central 2020-02-28            299        327
17451   international business park 2020-02-28            181        185
17452                 istana negara 2020-02-28            253        342
17469                        katong 2020-02-28            379        389
17496                       malcolm 2020-02-28            177        195
17506                     marymount 2020-02-28            573        580
17513                   mount emily 2020-02-28            178        200
17520                 newton circus 2020-02-28            130        167
17527               pasir panjang 1 2020-02-28            240        285
17533                      paterson 2020-02-28            118        151
17555                robertson quay 2020-02-28            346        393
17572             serangoon central 2020-02-28            760        816
17584                      somerset 2020-02-28            549        789
17596                       tanglin 2020-02-28            129        144
17598                 tanjong pagar 2020-02-28            231        267
17604             telok blangah way 2020-02-28            247        267
17643                yishun central 2020-02-28            332        347
17661              bayfront subzone 2020-02-29            196        228
17664               bedok reservoir 2020-02-29            596        605
17671                     boat quay 2020-02-29            838       1457
17675                     boulevard 2020-02-29            767        903
17677                    bras basah 2020-02-29            286        298
17679                         bugis 2020-02-29            680        687
17700                     city hall 2020-02-29           5780       6303
17703              clementi central 2020-02-29            710        773
17716                   dhoby ghaut 2020-02-29            409        456
17718                       dunearn 2020-02-29            252        277
17723                  farrer court 2020-02-29            184        193
17741                      hillview 2020-02-29            430        500
17743                  holland road 2020-02-29            548        619
17746               hougang central 2020-02-29            442        451
17749              institution hill 2020-02-29            196        202
17751                 istana negara 2020-02-29            333        387
17781                   leonie hill 2020-02-29            185        223
17804                 marine parade 2020-02-29            944       1046
17819                 newton circus 2020-02-29            154        173
17828             pasir ris central 2020-02-29            753        776
17831                pasir ris west 2020-02-29            586        621
17832                      paterson 2020-02-29            167        218
17847           punggol town centre 2020-02-29            148        153
17854                robertson quay 2020-02-29            434        455
17883                      somerset 2020-02-29            710       1011
17912                    townsville 2020-02-29            513        521
17970                     boat quay 2020-03-01            680        985
18268                     boat quay 2020-03-02            780       1106
18566                     boat quay 2020-03-03            948       1246
19164                     boat quay 2020-03-05            514       1138
19193                     city hall 2020-03-05           5673       7204
19244                 istana negara 2020-03-05            363        507
19269                         kovan 2020-03-05           2477       2694
19376                      somerset 2020-03-05            487        547
19399                   tiong bahru 2020-03-05            518        520
19409                tuas promenade 2020-03-05              0          1
19449        ang mo kio town centre 2020-03-06            103        203
19463                     boat quay 2020-03-06            488        551
19492                     city hall 2020-03-06           6930       7240
19500                  commonwealth 2020-03-06             57        132
19511                    east coast 2020-03-06             22         43
19517                      fernvale 2020-03-06            369        402
19543                 istana negara 2020-03-06            395        599
19568                         kovan 2020-03-06           2698       2826
19589                 mandai estate 2020-03-06             18         25

In [7]:
df.groupby('subzone')['android_count'].sum().reset_index().sort_values('android_count').head(15)

                  subzone  android_count
196   pulau punggol timor              1
195   pulau punggol barat              8
268        tuas promenade            256
270   tuas view extension            838
269             tuas view           1326
85         greenwood park           1740
231         simpang north           1872
60           coney island           2774
0               admiralty           3877
257                tengeh           4645
197         punggol canal           4683
139    lorong halus north           5396
215        sembawang east           5801
232         simpang south           6474
1            airport road           7568

In [8]:
df.groupby('subzone')['android_count'].sum().reset_index().sort_values('android_count').tail(15)

                      subzone  android_count
13                bedok north         312353
9                   balestier         335906
300                    yunnan         336417
4                    aljunied         349524
276             upper thomson         353564
136             lorong ah soo         463472
244             tampines east         472077
224          serangoon garden         475476
126                     kovan         574231
39    central water catchment         809609
37                      cecil        1216293
11           bayfront subzone        2912474
57              clifford pier        3021373
21                  boat quay       34742668
50                  city hall       36295442

In [9]:
df.to_csv(SAVEPATH, index=False)