In [62]:
import os
import pandas as pd
import numpy as np
import geopandas as gpd
import fiona

fiona.drvsupport.supported_drivers["KML"] = (
    "rw"  # enable KML support which is disabled by default
)
import gc
import janitor 
pd.set_option("display.max_rows", 500)

from utilities import walk_through_files, auto_reduce_mem, get_html_table_metadata
import osmnx
import warnings
warnings.filterwarnings('ignore')

In [36]:
FP_SUBZONES_SHP = os.path.join(
    "zip://" "./",
    "raw-data",
    "master-plan-2014-subzone-boundary-no-sea",
    "master-plan-2014-subzone-boundary-no-sea-kml.zip",
)
FP_PARKS = os.path.join("raw-data", "poi", "parks", "parks-geojson.geojson")
FP_LIB = os.path.join("raw-data", "poi", "libraries", "libraries-geojson.geojson")
FP_TRANSIT = os.path.join(
    "raw-data",
    "poi",
    "lta-mrt-station-exit",
    "lta-mrt-station-exit-geojson.geojson",
)
FP_PRESCH = os.path.join(
    "raw-data",
    "poi",
    "pre-schools-location",
    "pre-schools-location-geojson.geojson",
)
FP_SPORT = os.path.join(
    "raw-data",
    "poi",
    "sportsg-sport-facilities",
    "sportsg-sport-facilities-geojson.geojson",
)
FP_MART = os.path.join(
    "raw-data", "poi", "supermarkets", "supermarkets-geojson.geojson"
)
FP_SCHZONE = os.path.join(
    "raw-data", "poi", "lta-school-zone", "lta-school-zone-kml.kml"
)
FP_SILVER = os.path.join(
    "raw-data", "poi", "lta-silver-zone", "lta-silver-zone-kml.kml"
)
FP_TOURIST = os.path.join(
    "zip://",
    "raw-data",
    "poi",
    "tourist-attractions",
    "tourist-attractions-kml.zip",
)
FP_LRT = os.path.join(
    "raw-data", "poi", "singapore-postal-codes-master", "lrt_stations.json"
)
FP_MRT = os.path.join(
    "raw-data", "poi", "singapore-postal-codes-master", "mrt_stations.json"
)
FP_BUILDINGS = os.path.join(
    "raw-data", "poi", "singapore-postal-codes-master", "buildings.json"
)

# FP_REG_BUSINESS = os.path.join(
#     "..", "..", "wgw-lf", "acra-information-on-corporate-entities"
# )
FP_REG_BUSINESS = os.path.join("raw-data", "ACRAInformationonCorporateEntities")
FP_XWALK_ZIP_SUBZONE = os.path.join(
    "intermediate-output", "fixed_postal_subzone_xwalk.csv"
)

FP_HAWKERS = os.path.join("raw-data", "HawkerCentresGEOJSON.geojson")

SAVEPATH = os.path.join("intermediate-output", "subzones-poi-count.csv")

In [37]:
xwalk = (
    pd.read_csv(FP_XWALK_ZIP_SUBZONE)
    .rename(columns={"POSTAL": "postcode", "subzone_name": "subzone"})
    .assign(postcode=lambda df: df["postcode"].astype("str").str.zfill(6))
)
xwalk.head(3)

  postcode          subzone
0   018906            CECIL
1   018907  CENTRAL SUBZONE
2   018910     MARINA SOUTH

### Data.gov.sg resources

In [39]:
subzones = (
    gpd.read_file(FP_SUBZONES_SHP)
    .rename(columns={"Name": "subzone"})
    .drop("Description", axis=1)
)
subzones.head(3)

         subzone                                           geometry
0  PEOPLE'S PARK  MULTIPOLYGON Z (((103.84319 1.28433 0, 103.842...
1    BUKIT MERAH  MULTIPOLYGON Z (((103.82209 1.28049 0, 103.822...
2      CHINATOWN  MULTIPOLYGON Z (((103.84375 1.28508 0, 103.843...

In [40]:
# Parks
parks = (
    gpd.read_file(FP_PARKS).rename(columns={"Name": "park"}).drop("Description", axis=1)
)

assert parks.crs == subzones.crs

parks = (
    gpd.sjoin(parks, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "parks"})
)
parks.head(3)

      subzone  parks
0    ALJUNIED      3
1  ANAK BUKIT      9
2   BALESTIER      2

In [41]:
# Libraries
lib = (
    gpd.read_file(FP_LIB)
    .rename(columns={"Name": "libraries"})
    .drop("Description", axis=1)
)

assert lib.crs == subzones.crs

lib = (
    gpd.sjoin(lib, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "libraries"})
)
lib.head(3)

                  subzone  libraries
0                ALJUNIED          1
1  ANG MO KIO TOWN CENTRE          1
2             BEDOK NORTH          1

In [42]:
# LRT & MRT stations
transit = (
    gpd.read_file(FP_TRANSIT)
    .rename(columns={"Name": "transit"})
    .drop("Description", axis=1)
)

assert transit.crs == subzones.crs

transit = (
    gpd.sjoin(transit, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "transit"})
)
transit.head(3)

      subzone  transit
0    ALJUNIED        8
1  ANAK BUKIT        3
2  ANCHORVALE        6

In [43]:
# Preschools
presch = (
    gpd.read_file(FP_PRESCH)
    .rename(columns={"Name": "preschools"})
    .drop("Description", axis=1)
)

assert presch.crs == subzones.crs

presch = (
    gpd.sjoin(presch, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "preschools"})
)

In [44]:
# Sport facilities
sport = (
    gpd.read_file(FP_SPORT)
    .rename(columns={"Name": "sport_facilities"})
    .drop("Description", axis=1)
)

assert sport.crs == subzones.crs

sport = (
    gpd.sjoin(sport, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "sport_facilities"})
)

In [45]:
# Supermarkets
marts = (
    gpd.read_file(FP_MART)
    .rename(columns={"Name": "supermarkets"})
    .drop("Description", axis=1)
)

assert marts.crs == subzones.crs

marts = (
    gpd.sjoin(marts, subzones, how="left", predicate="within")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "supermarkets"})
)

In [46]:
# LTA school zones
schzone = (
    gpd.read_file(FP_SCHZONE)
    .rename(columns={"Name": "schzone"})
    .drop("Description", axis=1)
)

assert schzone.crs == subzones.crs

schzone = (
    gpd.sjoin(schzone, subzones, how="left", predicate="intersects")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "schzones"})
)

In [47]:
# LTA silver zones
silver = (
    gpd.read_file(FP_SILVER)
    .rename(columns={"Name": "silverzones"})
    .drop("Description", axis=1)
)

assert silver.crs == subzones.crs

silver = (
    gpd.sjoin(silver, subzones, how="left", predicate="intersects")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "silverzones"})
)

In [48]:
# Tourist attractions
tour = (
    gpd.read_file(FP_TOURIST)
    .rename(columns={"Name": "tourist_attraction"})
    .drop("Description", axis=1)
)

assert tour.crs == subzones.crs

tour = (
    gpd.sjoin(tour, subzones, how="left", predicate="intersects")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "tour"})
)

### Open-source resources

#### Schools

In [49]:
poi = (
    pd.read_json(FP_BUILDINGS)
    .rename(columns={"BUILDING": "poi", "POSTAL": "postcode"})
    .filter(["poi", "postcode"])
    .assign(poi=lambda df: df["poi"].str.lower())
)

schools = poi[
    (poi["poi"].str.contains("primary school"))
    | (poi["poi"].str.contains("secondary school"))
]

del poi
gc.collect()

# Merge schools with postcode to subzone crosswalk
schools = (
    schools.merge(xwalk, how="left", on="postcode")
    .drop("postcode", axis=1)
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "schools"})
)

#### Transit

In [50]:
lrts = (
    pd.read_json(FP_LRT)
    .rename(columns={"Possible Locations": "geopayload"})
    .explode("geopayload")
    .query("geopayload==geopayload")
    .assign(postcode=lambda df: [js["POSTAL"] for js in df["geopayload"]])
    .drop_duplicates("Station")
    .merge(xwalk, how="left", on="postcode")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "lrts"})
)

In [51]:
mrts = (
    pd.read_json(FP_MRT)
    .rename(columns={"Possible Locations": "geopayload"})
    .explode("geopayload")
    .query("geopayload==geopayload")
    .assign(postcode=lambda df: [js["POSTAL"] for js in df["geopayload"]])
    .drop_duplicates("Station")
    .merge(xwalk, how="left", on="postcode")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "mrts"})
)

#### Distribution of industry groups
Resources on SSIC:

* https://stats.mom.gov.sg/Pages/Employment-Distribution-and-Employment-Level-by-Industry.aspx\
* https://www.singstat.gov.sg/standards/standards-and-classifications/ssic
* https://www.singstat.gov.sg/-/media/files/standards_and_classifications/industrial_classification/ssic2020report.pdf

3 Biggest "Industry groups:

1. Manufacturing 10
2. construction 41
3. Services:
* wholesale 46
* retail trade 47
* Transport & storage 49
* Land transport & Support svcs 49?

In [53]:
csv_files = list(walk_through_files(FP_REG_BUSINESS, "csv", fullpath=True))
dfs = []
for file in csv_files:
    df = pd.read_csv(file, low_memory=False)
    dfs.append(df)

df = (
    pd.concat(dfs, ignore_index=True)
    .assign(
        entity_status_description=lambda df: df["entity_status_description"].str.lower()
    )
    .assign(
        entity_status_description=lambda df: df[
            "entity_status_description"
        ].str.replace("live company", "live")
    )
    .query('entity_status_description=="live"')
    .query('uen_issue_date <= "2020-01-01"')
    .rename(columns={"primary_ssic_code": "ssic"})
    .pipe(lambda df: df[["postal_code", "ssic"]])
    .astype({"ssic": "str"})
    .assign(ind=lambda df: df["ssic"].str.zfill(5).str.slice(stop=2))
    .groupby(["postal_code", "ind"])
    .size()
    .reset_index()
    .rename(columns={0: "count", "postal_code": "postcode"})
)

manufact = df[df["ind"] == "10"]
construct = df[df["ind"] == "41"]
services = df[(df["ind"] == "46") | (df["ind"] == "47") | (df["ind"] == "49")]

df.head()

  postcode ind  count
0   018906  90      2
1   018906  94      1
2   018916  46      1
3   018916  64      8
4   018916  65      1

In [54]:
manufact = (
    manufact.merge(xwalk, how="left", on="postcode")
    .groupby("subzone")["count"]
    .sum()
    .reset_index()
    .rename(columns={"count": "manufacturing"})
)


construct = (
    construct.merge(xwalk, how="left", on="postcode")
    .groupby("subzone")["count"]
    .sum()
    .reset_index()
    .rename(columns={"count": "construction"})
)


services = (
    services.merge(xwalk, how="left", on="postcode")
    .groupby("subzone")["count"]
    .sum()
    .reset_index()
    .rename(columns={"count": "services"})
)

### New

#### Hawkers

In [58]:
gdf_hawkers = (
    gpd.read_file(FP_HAWKERS)
    .pipe(get_html_table_metadata)
    .query("STATUS!='Under Construction'")
    # keep those before 2020
    .assign(
        completion_date=lambda df_: pd.to_datetime(df_["EST_ORIGINAL_COMPLETION_DATE"], errors='coerce'),
        completion_year=lambda df_: np.where(df_["completion_date"].isna(), 
                                             df_["EST_ORIGINAL_COMPLETION_DATE"], 
                                             df_["completion_date"].dt.year),
    )
    .replace("Pre-War", 1990)
    .assign(completion_year=lambda df_: df_["completion_year"].fillna(1900).apply(int))
    .query('completion_year<2020')
    .reset_index()
    .assign(postcode=lambda df_: df_["ADDRESSPOSTALCODE"].astype("str").str.zfill(6))
    .filter(["postcode"])
)
gdf_hawkers.head()

  postcode
0   738623
1   460538
2   460085
3   289876
4   380117

In [59]:
hawkers = (
    gdf_hawkers
    .merge(xwalk, how="left", on="postcode")
    .drop("postcode", axis=1)
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "hawkers"})
)
hawkers.head()

                  subzone  hawkers
0          ALEXANDRA HILL        4
1                ALJUNIED        6
2              ANAK BUKIT        1
3  ANG MO KIO TOWN CENTRE        1
4               BALESTIER        2

#### Shopping malls

In [68]:
# https://wiki.openstreetmap.org/wiki/Tag:shop%3Dmall
payload = osmnx.features_from_place("Singapore", tags={'shop': 'mall'})

priority_order = {
   'way': 1,      # Building footprints - most accurate for mall boundaries
   'node': 2,     # Point locations - simple but less detailed
   'relation': 3  # Complex structures - often contain duplicate data from member ways
}

gdf_malls = (
    payload
    .clean_names()
    .reset_index()
    .query("addr_housename==addr_housename | name==name")
    .assign(name=lambda df_: np.where(df_["name"].isna(), df_["addr_housename"], df_["name"]))
    # Dedup
    .assign(priority=lambda df_: df_['element'].map(priority_order))
    .sort_values('priority')
    .drop_duplicates(subset=['name'], keep='first', ignore_index=True)
    .remove_columns('priority')
    # get centroid for PIP
    .assign(centroid=lambda df_: df_['geometry'].centroid)
    .remove_columns("geometry")
    .rename_column("centroid", "geometry")
)
gdf_malls

,element,id,addr_city,addr_country,addr_housename,addr_housenumber,addr_postcode,addr_street,bench,bin,...,short_name_zh,building_use,postal_code,opening_date,roof_height,old_name_1983_1995,old_name_1995_2011,type,architect,geometry
0,way,32774317,NaN,NaN,NaN,118,540118,Rivervale Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90185 1.3854)
1,way,26561741,Singapore,SG,NaN,80,819642,Airport Boulevard,NaN,NaN,...,1号航站楼,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.99064 1.36237)
2,way,32416309,Singapore,SG,Broadway Plaza,4190,569841,Ang Mo Kio Avenue 6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84596 1.37194)
3,way,30527021,Singapore,SG,NaN,1,188504,Rochor Canal Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85303 1.30303)
4,way,32774374,Singapore,NaN,NaN,11,545082,Rivervale Crescent,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90446 1.39219)
5,way,32774292,Singapore,SG,NaN,1,545078,Sengkang Square,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89496 1.39204)
6,way,45107961,Singapore,SG,NaN,150,238841,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84113 1.30126)
7,way,45066510,Singapore,SG,NaN,50,428769,East Coast Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90461 1.30335)
8,way,44414531,Singapore,SG,NaN,231,180231,Bain Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85362 1.29682)
9,way,44348658,Singapore,NaN,NaN,NaN,NaN,Mountbatten Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90192 1.30467)
10,way,44348592,Singapore,SG,NaN,865,437844,Mountbatten Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90114 1.30386)
11,way,44348591,Singapore,SG,NaN,1,429979,Brooke Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90389 1.30419)
12,way,44121574,Singapore,NaN,112 Katong,112,428802,East Coast Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Katong People's Complex,Katong Mall,NaN,NaN,POINT (103.90501 1.3052)
13,way,44121572,Singapore,SG,Parkway Parade,80,449269,Marine Parade Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90523 1.30131)
14,way,43755568,Singapore,SG,NaN,100,079027,Tras Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84361 1.27491)
15,way,42010371,NaN,NaN,NaN,8,239695,Grange Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83647 1.30146)
16,way,41913930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.80348 1.28761)
17,way,41913741,Singapore,SG,NaN,370,159953,Alexandra Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.80508 1.2887)
18,way,41890235,Singapore,SG,NaN,400,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8292 1.30696)
19,way,41890217,Singapore,SG,NaN,390,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82965 1.30672)
20,way,41889999,Singapore,NaN,Orchard Central,181,238896,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83983 1.30067)
21,way,41889431,NaN,NaN,Shaw House,350,238868,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83151 1.30579)
22,way,39487263,Singapore,SG,NaN,252,179103,North Bridge Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85334 1.29391)
23,way,37357018,Singapore,SG,NaN,61,569814,Ang Mo Kio Avenue 8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84777 1.37178)
24,way,34575159,Singapore,SG,White Sands,1,518457,Pasir Ris Central Street 3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.94973 1.37245)
25,way,33543880,Singapore,SG,NaN,2,609601,Jurong East Street 21,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.7468 1.33489)
26,way,33444529,Singapore,NaN,NaN,205,530205,Hougang Street 21,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.88521 1.35946)
27,way,32774665,Singapore,SG,Hougang Mall,90,538766,Hougang Avenue 10,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89377 1.37246)
28,way,32774612,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8879 1.37932)
29,way,46518144,NaN,NaN,Pacific Plaza,9,228210,Scotts Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83212 1.30656)
30,way,46503585,Singapore,SG,NaN,176,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83979 1.30189)
31,way,46503590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84771 1.29949)
32,way,46515799,Singapore,NaN,Ngee Ann City,391,238872,Orchard Rd,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83476 1.30259)
33,way,46522843,Singapore,NaN,NaN,1,188306,Selegie Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84931 1.30015)
34,way,46522833,Singapore,NaN,NaN,35,188307,Selegie Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84945 1.30065)
35,way,46529040,Singapore,SG,NaN,91,189652,Bencoolen Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85094 1.30036)
36,way,116782195,Singapore,SG,NaN,445,469661,Bedok North Street 1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.92955 1.32613)
37,way,111610945,Singapore,SG,NaN,51,390051,Old Airport Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8858 1.30826)
38,way,111151622,Singapore,SG,NaN,321,159972,Alexandra Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.80533 1.28729)
39,way,107578653,Singapore,NaN,NaN,1,538692,Hougang Street 91,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.87952 1.37571)
40,way,104352121,Singapore,SG,The Star Vista,1,138617,Vista Exchange Green,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.78846 1.30688)
41,way,102429452,Singapore,SG,City Square Mall,180,208539,Kitchener Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85658 1.31141)
42,way,95939467,Singapore,SG,NaN,762,640762,Jurong West Street 75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.69763 1.34894)
43,way,95594924,Singapore,SG,NaN,638,640638,Jurong West Street 61,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.69717 1.3417)
44,way,94018008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.70523 1.33945)
45,way,72660563,Singapore,SG,NaN,248,520248,Simei Street 3,NaN,NaN,...,NaN,carpark;shops,520248,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.95362 1.34351)
46,way,62204073,Sembawang,NaN,NaN,604,758459,Sembawang Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82496 1.44187)
47,way,54032324,Singapore,SG,Depot Heights Shopping Centre,108,100108,Depot Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.81034 1.28118)
48,way,52236347,Singapore,SG,NaN,313,238895,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83837 1.30102)
49,way,48581160,Singapore,SG,NaN,30,757713,Sembawang Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.81952 1.4482)
50,way,48031573,Singapore,NaN,NaN,201,188067,Victoria Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85418 1.29966)
51,way,47345027,Singapore,SG,NaN,6,NaN,Shenton Way,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84867 1.2774)
52,way,47198841,NaN,NaN,NaN,145,NaN,Syed Alwi Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85532 1.31012)
53,way,47198835,Singapore,SG,NaN,665,210665,Buffalo Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85059 1.3062)
54,way,46919233,Singapore,SG,NaN,810,409286,Geylang Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89343 1.31477)
55,way,46919229,Singapore,SG,Tanjong Katong Complex,845,400845,Geylang Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89436 1.31637)
56,way,46821373,Singapore,SG,NaN,NaN,NaN,Simei Street 6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.953 1.34273)
57,way,46612311,Singapore,SG,NaN,163,247933,Tanglin Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82384 1.30484)
58,way,46595137,Singapore,SG,Suntec City Mall,3,038983,Temasek Boulevard,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8579 1.29508)
59,way,46594832,Singapore,SG,NaN,111,179098,North Bridge Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85083 1.29233)
60,way,46529046,Singapore,NaN,NaN,190,NaN,Middle Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85226 1.30038)
61,way,139670204,NaN,NaN,NaN,756,534626,Upper Serangoon Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.87881 1.35358)
62,way,144381429,Singapore,SG,West Coast Plaza,154,127371,West Coast Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.76613 1.30368)
63,way,152598430,Singapore,SG,NaN,10,078878,Gopeng St,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8445 1.27514)
64,way,152638469,Singapore,NaN,NaN,211,278967,Holland Avenue,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.79537 1.31029)
65,way,152752624,Singapore,NaN,NaN,3,277725,Lorong Liput,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.79526 1.31069)
66,way,153136696,Singapore,NaN,Ang Mo Kio Hub,53,569933,Ang Mo Kio Avenue 3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84841 1.3694)
67,way,154157497,NaN,NaN,NaN,678A,NaN,Woodlands Avenue 6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8013 1.44026)
68,way,154178431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.87654 1.30221)
69,way,154493306,Singapore,SG,NaN,402,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82847 1.30717)
70,way,155096524,Singapore,NaN,Orchard Building,1,239693,Grange Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83736 1.30141)
71,way,155991343,Singapore,NaN,NaN,2,NaN,Serangoon Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85228 1.30455)
72,way,158234014,Singapore,SG,NaN,3,608532,Gateway Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.74285 1.3342)
73,way,159940901,Singapore,NaN,NaN,587,269707,Bukit Timah Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.81001 1.32378)
74,way,161136289,Singapore,SG,NaN,1,237994,Kim Seng Promenade,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83193 1.29357)
75,way,162524446,Singapore,SG,West Mall,1,658713,Bukit Batok Central Link,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.74926 1.35001)
76,way,166194030,Singapore,SG,NaN,4,529509,Tampines Central 5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.9447 1.35248)
77,way,166194031,Singapore,SG,NaN,2,529509,Tampines Central 5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.94382 1.35238)
78,way,166194476,Singapore,SG,NaN,10,529536,Tampines Central 1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.94506 1.35421)
79,way,167472305,Singapore,NaN,NaN,35,138639,Rochester Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.78815 1.30561)
80,way,170403710,Singapore,SG,NaN,480,310480,Lorong 6 Toa Payoh,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84851 1.33204)
81,way,172024056,Singapore,SG,NaN,317,169075,Outram Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83417 1.28894)
82,way,172117296,NaN,NaN,NaN,302,NaN,Tiong Bahru Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82729 1.28642)
83,way,172364977,Singapore,SG,NaN,200,188021,Victoria Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85593 1.29984)
84,way,172518481,Singapore,SG,NaN,545,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83009 1.30554)
85,way,172518487,Singapore,SG,NaN,583,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82867 1.30609)
86,way,117035196,Singapore,SG,NaN,301,574408,Upper Thomson Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83074 1.35457)
87,way,117450953,Singapore,SG,NaN,170,588179,Upper Bukit Timah Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.77599 1.34319)
88,way,117450954,Singapore,SG,NaN,144,588177,Upper Bukit Timah Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.77657 1.34234)
89,way,117450957,Singapore,NaN,NaN,140,588176,Upper Bukit Timah Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.77626 1.34181)
90,way,118994815,Singapore,SG,The Clementi Mall,3155,129588,Commonwealth Avenue West,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.76427 1.31493)
91,way,119879842,Singapore,NaN,NaN,3151,129581,Commonwealth Avenue West,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.76514 1.3143)
92,way,127548081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8694 1.3875)
93,way,172518499,Singapore,SG,NaN,320,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83302 1.30503)
94,way,172518491,Singapore,SG,NaN,541,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83072 1.30509)
95,way,172518492,Singapore,SG,NaN,304,238863,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83398 1.30448)
96,way,172518496,Singapore,SG,NaN,290,238859,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83568 1.30384)
97,way,172521292,Singapore,SG,NaN,260,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83737 1.30261)
98,way,172518503,Singapore,SG,NaN,435,238877,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83322 1.3037)
99,way,172529118,Singapore,NaN,NaN,238,307683,Thomson Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84389 1.31986)
100,way,222839548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85366 1.2808)
101,way,222839479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8552 1.29285)
102,way,222839478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85449 1.29227)
103,way,218269179,Singapore,NaN,NaN,60,409051,Paya Lebar Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.8926 1.31881)
104,way,218215289,Singapore,NaN,NaN,168,820168,Punggol Field,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.91305 1.39424)
105,way,213582607,Singapore,SG,NaN,258,NaN,Pasir Ris Drive 2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.96463 1.36701)
106,way,201904038,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89838 1.3159)
107,way,182867955,Singapore,NaN,NaN,360,329783,Balestier Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.85118 1.32504)
108,way,182848383,Singapore,SG,NaN,475,680475,Choa Chu Kang Avenue 3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.73907 1.3778)
109,way,182822197,Singapore,SG,NaN,277,238858,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83923 1.30061)
110,way,182822196,Singapore,SG,NaN,220,NaN,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83865 1.30176)
111,way,175841411,Singapore,SG,NaN,1,138632,Fusionopolis Way,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.78756 1.29919)
112,way,174035941,Singapore,SG,NaN,23,556083,Serangoon Central,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.87232 1.35056)
113,way,173235510,Singapore,NaN,NaN,1,519599,Pasir Ris Close,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.95463 1.37706)
114,way,173222209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.82707 1.29303)
115,way,173144799,Singapore,SG,NaN,1,677743,Jelebu Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.76431 1.38001)
116,way,173131856,Singapore,SG,NaN,21,689812,Choa Chu Kang Avenue 4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.74496 1.38515)
117,way,173028320,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.96558 1.33346)
118,way,173010413,Singapore,SG,NaN,65,819663,Airport Boulevard,NaN,NaN,...,3号航站楼,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.98592 1.35532)
119,way,173010412,Singapore,SG,NaN,60,819643,Airport Boulevard,NaN,NaN,...,2号航站楼,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.98972 1.35469)
120,way,172529122,Singapore,SG,NaN,101,307591,Thomson Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84363 1.31717)
121,way,172529121,Singapore,NaN,NaN,10,307506,Sinaran Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84412 1.32075)
122,way,430678763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83293 1.30583)
123,way,432515092,Singapore,SG,NaN,107,179105,North Bridge Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84994 1.29142)
124,way,432868544,Singapore,SG,NaN,321,120321,Clementi Avenue 3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.76502 1.31198)
125,way,445001361,Singapore,SG,NaN,598,768698,Yishun Ring Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84126 1.41821)
126,way,446775872,Singapore,SG,NaN,18,539775,Tai Seng Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.88882 1.33631)
127,way,447213139,Singapore,SG,NaN,501,238880,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83064 1.30466)
128,way,455200744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84167 1.43311)
129,way,463063306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.89481 1.31898)
130,way,465145060,Singapore,SG,NaN,12,339511,Kallang Avenue,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.86401 1.31031)
131,way,474909150,NaN,NaN,NaN,NaN,NaN,MacPherson Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.87933 1.33179)
132,way,502013652,Singapore,NaN,NaN,4,738623,Woodlands Street 12,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.77988 1.43355)
133,way,510901696,Singapore,SG,Downtown Gallery,6A,068815,Shenton Way,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84837 1.2769)
134,way,539668158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83072 1.30509)
135,way,539767937,Singapore,SG,NaN,68,238839,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84524 1.30032)
136,way,543400239,Singapore,SG,NaN,87,118260,Science Park Drive,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.79038 1.28772)
137,way,547383951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2019,NaN,NaN,NaN,NaN,NaN,POINT (103.98977 1.36027)
138,way,561552023,Singapore,NaN,NaN,86,428788,East Coast Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90473 1.30472)
139,way,561552026,Singapore,SG,The Flow,66,NaN,East Coast Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.90427 1.30456)
140,way,599416637,Singapore,SG,NaN,4,657991,Bukit Batok Street 41,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.74113 1.35595)
141,way,620515713,Singapore,SG,NaN,9,579837,Bishan Place,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84869 1.35059)
142,way,655792110,Singapore,NaN,NaN,250,238905,Orchard Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83793 1.30207)
143,way,675585724,Singapore,NaN,NaN,12,465492,New Upper Changi Road,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.92929 1.32476)
144,way,699168484,Singapore,NaN,NaN,6,059817,Eu Tong Sen Street,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.84668 1.28907)
145,way,707600485,Singapore,SG,NaN,930,769098,Yishun Avenue 2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.83611 1.42816)
146,way,224318439,Singapore,NaN,NaN,21,689578,Choa Chu Kang North 6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (103.74664 1.39707)

In [76]:
assert gdf_malls.crs == subzones.crs
shopping_malls = (
    gpd.sjoin(gdf_malls, subzones, how="left", predicate="intersects")
    .groupby("subzone")
    .size()
    .reset_index()
    .rename(columns={0: "shopping_malls"})    
)
shopping_malls.head()

                  subzone  shopping_malls
0          ALEXANDRA HILL               1
1                ALJUNIED               2
2              ANAK BUKIT               3
3  ANG MO KIO TOWN CENTRE               3
4                   ANSON               1

### Merge all

In [ ]:
df_list_toappend = [
    lib,
    marts,
    parks,
    presch,
    schzone,
    silver,
    sport,
    transit,
    tour,
    schools,
    mrts,
    lrts,
    manufact,
    construct,
    services,
    hawkers,
    shopping_malls,
]

# Merge
df = subzones[["subzone"]]

for _pddf in df_list_toappend:
    df = df.merge(_pddf, how="outer", on="subzone")

for _pddf in df_list_toappend:
    del _pddf
    gc.collect()

df.fillna(0, inplace=True)

auto_reduce_mem(df, downcast_float="integer")

In [ ]:
df

In [ ]:
df.to_csv(SAVEPATH, index=False)