In [1]:
import pandas as pd

In [2]:
df_new = pd.read_csv("output/cd-panel.csv")
df_new

/tmp/ipykernel_2015/804783087.py:1: DtypeWarning: Columns (33,35,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df_new = pd.read_csv("output/cd-panel.csv")

,date,home,inflow,basecount,dest_basecount,area,pa_home,htype_home,resident_count_home,private_home,...,wpsm_home,wpsm_private_dest,wpsm_public_dest,wpsm_dest,wprice_private_home,wprice_public_home,wprice_home,wprice_private_dest,wprice_public_dest,wprice_dest
0,2020-01-01,0,14.583333,48,24,0,36,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,14110,0.00000,...,3930.897154,NaN,3930.897154,3930.897154,NaN,369809.569519,369809.569519,NaN,369809.569519,369809.569519
1,2020-01-01,0,2.083333,48,83,8,36,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,14110,0.00000,...,3930.897154,NaN,NaN,NaN,NaN,369809.569519,369809.569519,0.000000,NaN,NaN
2,2020-01-01,0,2.083333,48,1125,9,36,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,14110,0.00000,...,3930.897154,4673.847113,3244.201532,7918.048645,NaN,369809.569519,369809.569519,0.000000,433557.770270,433557.770270
3,2020-01-01,0,2.083333,48,21929,11,36,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,14110,0.00000,...,3930.897154,NaN,NaN,NaN,NaN,369809.569519,369809.569519,NaN,NaN,NaN
4,2020-01-01,0,2.083333,48,691,20,36,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,14110,0.00000,...,3930.897154,1644.481157,5253.144564,6897.625720,NaN,369809.569519,369809.569519,0.000000,611378.162749,611378.162749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2103962,2020-03-31,296,0.141643,706,286,294,16,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,67890,11.16512,...,3880.279499,635.689680,3872.795202,4508.484881,115654.575654,329388.979813,445043.555467,106077.047221,345549.124300,451626.171521
2103963,2020-03-31,296,0.283286,706,464,296,16,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,67890,11.16512,...,3880.279499,1031.191328,3348.374871,4379.566199,115654.575654,329388.979813,445043.555467,105708.999243,276200.873692,381909.872935
2103964,2020-03-31,296,0.849858,706,200,297,16,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,67890,11.16512,...,3880.279499,990.616324,3714.970215,4705.586539,115654.575654,329388.979813,445043.555467,146167.868124,328916.588415,475084.456539
2103965,2020-03-31,296,0.424929,706,149,298,16,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,67890,11.16512,...,3880.279499,1529.326101,3400.410630,4929.736731,115654.575654,329388.979813,445043.555467,119039.196529,352332.961113,471372.157642
2103966,2020-03-31,296,54.957507,706,880,299,16,HDB 1- and 2-Room FlatsHDB 3-Room FlatsHDB 4-R...,67890,11.16512,...,3880.279499,907.080439,2973.199059,3880.279499,115654.575654,329388.979813,445043.555467,115654.575654,329388.979813,445043.555467

In [5]:
df_new[df_new.duplicated(["home", "area", "date"])]

Empty DataFrame
Columns: [date, home, inflow, basecount, dest_basecount, area, pa_home, htype_home, resident_count_home, private_home, rm12_home, rm3_home, rm4_home, rm5_home, pa_dest, htype_dest, resident_count_dest, private_dest, rm12_dest, rm3_dest, rm4_dest, rm5_dest, rain_home, rain_dest, centroid_distance, edge_distance, centroid_distance_epsg, edge_distance_epsg, area_o, region_o, area_d, region_d, females_o, gender_o_x, age_20_o, gender_o_y, age20_40_o, gender_o, age65__o, females_d, gender_d_x, age_20_d, gender_d_y, age20_40_d, gender_d, age65__d, chinese_o, malays_o, indians_o, others_o, chinese_d, malays_d, indians_d, others_d, libraries, supermarkets, parks, preschools, schzones, silverzones, sport_facilities, transit, tour, schools, mrts, lrts, manufacturing, construction, services, total_dwelling_units_home, rm12_rental_pct_home, rental_pct_home, total_dwelling_units_dest, rm12_rental_pct_dest, rental_pct_dest, num_transactions_home, psm_home, price_home, num_transactions_dest, psm_dest, price_dest, public_num_transactions_home, public_psm_home, public_price_home, public_num_transactions_dest, public_psm_dest, public_price_dest, private_num_transactions_home, private_psm_home, private_price_home, private_num_transactions_dest, private_psm_dest, private_price_dest, wpsm_private_home, wpsm_public_home, wpsm_home, wpsm_private_dest, wpsm_public_dest, wpsm_dest, wprice_private_home, ...]
Index: []

[0 rows x 105 columns]

In [3]:
print(df_new[["date", "home", "area"]].nunique())

date     91
home    297
area    300
dtype: int64

In [14]:
print(df_old[["date", "home", "area"]].nunique())

date     91
home    297
area    300
dtype: int64

In [3]:
df_old = pd.read_csv("../analysis/cd-panel.csv")
df_old

,date,home,inflow,basecount,dest_basecount,area,pa_home,resident_count_home,private_home,rm12_home,...,wpsm_home,wpsm_private_dest,wpsm_public_dest,wpsm_dest,wprice_private_home,wprice_public_home,wprice_home,wprice_private_dest,wprice_public_dest,wprice_dest
0,2020-01-01,0,14.583333,48,24,0,36,14110,0.000000,8.079376,...,3930.897154,NaN,3930.897154,3930.897154,NaN,369809.569519,3.698096e+05,NaN,369809.569519,369809.569519
1,2020-01-01,37,0.019914,15065,24,0,12,200,100.000000,0.000000,...,22025.536145,NaN,3930.897154,3930.897154,1.889564e+06,NaN,1.889564e+06,NaN,0.000000,NaN
2,2020-01-01,105,0.735294,136,24,0,15,440,100.000000,0.000000,...,18756.772727,NaN,3930.897154,3930.897154,1.109993e+06,NaN,1.109993e+06,NaN,0.000000,NaN
3,2020-01-01,146,0.534759,187,24,0,19,0,NaN,NaN,...,NaN,NaN,3930.897154,3930.897154,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-01,212,4.365079,252,24,0,36,34010,11.555425,3.998824,...,4264.948020,NaN,3930.897154,3930.897154,9.825416e+04,363182.823702,4.614370e+05,NaN,327076.502532,327076.502532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2103962,2020-03-31,279,0.482315,622,880,299,50,98410,4.593029,2.865562,...,3715.999989,907.080439,2973.199059,3880.279499,3.861212e+04,356752.386516,3.953645e+05,47577.172180,353757.497139,401334.669319
2103963,2020-03-31,292,0.297619,336,880,299,51,41850,6.977300,2.198327,...,4188.970553,907.080439,2973.199059,3880.279499,6.548503e+04,373249.879268,4.387349e+05,72274.785537,344916.909980,417191.695516
2103964,2020-03-31,294,1.477833,203,880,299,15,24650,10.669371,0.000000,...,4705.586539,907.080439,2973.199059,3880.279499,1.396778e+05,330752.128921,4.704299e+05,110519.331010,331227.156530,441746.487541
2103965,2020-03-31,295,1.863354,161,880,299,15,19330,16.037248,9.001552,...,4929.736731,907.080439,2973.199059,3880.279499,1.709844e+05,333009.344089,5.039937e+05,166122.807574,311323.719958,477446.527532
2103966,2020-03-31,296,54.957507,706,880,299,16,67890,11.165120,1.959051,...,3880.279499,907.080439,2973.199059,3880.279499,1.156546e+05,329388.979813,4.450436e+05,115654.575654,329388.979813,445043.555467

In [7]:
df_old[df_old.duplicated(["home", "area", "date"])]

Empty DataFrame
Columns: [date, home, inflow, basecount, dest_basecount, area, pa_home, resident_count_home, private_home, rm12_home, rm3_home, rm4_home, rm5_home, pa_dest, resident_count_dest, private_dest, rm12_dest, rm3_dest, rm4_dest, rm5_dest, rain_home, rain_dest, centroid_distance, edge_distance, centroid_distance_epsg, edge_distance_epsg, area_o, region_o, area_d, region_d, females_o, age_20_o, age20_40_o, age65__o, females_d, age_20_d, age20_40_d, age65__d, chinese_o, malays_o, indians_o, others_o, chinese_d, malays_d, indians_d, others_d, libraries, supermarkets, parks, preschools, schzones, silverzones, sport_facilities, transit, tour, schools, mrts, lrts, manufacturing, construction, services, total_dwelling_units_home, rm12_rental_pct_home, rental_pct_home, total_dwelling_units_dest, rm12_rental_pct_dest, rental_pct_dest, num_transactions_home, psm_home, price_home, num_transactions_dest, psm_dest, price_dest, public_num_transactions_home, public_psm_home, public_price_home, public_num_transactions_dest, public_psm_dest, public_price_dest, private_num_transactions_home, private_psm_home, private_price_home, private_num_transactions_dest, private_psm_dest, private_price_dest, wpsm_private_home, wpsm_public_home, wpsm_home, wpsm_private_dest, wpsm_public_dest, wpsm_dest, wprice_private_home, wprice_public_home, wprice_home, wprice_private_dest, wprice_public_dest, wprice_dest]
Index: []

[0 rows x 97 columns]

## Step 3

In [15]:
df_out3 = pd.read_csv("intermediate-files/device-area-maxcount.csv.gz")
df_out3

          device_xid  area_id  count
0            3722850       46     11
1           10776333      110      1
2           10928622       21     71
3           16218465       21     60
4             683572      288     20
...              ...      ...    ...
41107806     8701578      104      1
41107807     7407067       67      1
41107808     9726798      163      1
41107809     7452823       37      1
41107810    17443674      227      1

[41107811 rows x 3 columns]