In [1]:
import os
import pandas as pd
from tqdm.notebook import tqdm

from utilities import get_date, walk_through_files, get_subzone_name_from_dir

pd.set_option("display.max_rows", 500)

RECORDS_PATH = os.path.join("raw-data", "sg_subzones_devices", "sg_subzones_devices")
SAVEPATH = os.path.join("intermediate-files", "devicecount-subzone-day.csv")

In [2]:
ix = 0
dict_placeholder = {}


for filepath in tqdm(walk_through_files(RECORDS_PATH, "csv.gz", fullpath=True)):

    # parse file name to get date and loc
    try:
        subzone = get_subzone_name_from_dir(filepath)
        date = get_date(filepath)
    except ValueError:
        print(filepath)

    # read into df
    _df = pd.read_csv(
        filepath,
        compression="gzip",
        names=["id", "os"],
        dtype={"id": "object", "os": "int8"},
    )

    android_count = len(_df[_df["os"] == 0])
    ios_count = len(_df[_df["os"] == 1])

    # init list and add to dict
    dict_placeholder[ix] = [subzone, date, android_count, ios_count]

    ix += 1

0it [00:00, ?it/s]

In [5]:
df = (
    pd.DataFrame.from_dict(
        dict_placeholder,
        orient="index",
        columns=["subzone", "date", "android_count", "ios_count"],
    )
    .astype(
        {
            "subzone": "object",
            "date": "datetime64[ns]",
            "android_count": "int",
            "ios_count": "int",
        }
    )
    .drop_duplicates(["subzone", "date"], ignore_index=True)
    .sort_values(["date", "subzone"], ignore_index=True)
)

df.head(10)

                  subzone       date  android_count  ios_count
0               admiralty 2020-01-01             63         10
1            airport road 2020-01-01             54          3
2          alexandra hill 2020-01-01           1080        203
3         alexandra north 2020-01-01            362         74
4                aljunied 2020-01-01           5687       1033
5              anak bukit 2020-01-01           1296        310
6              anchorvale 2020-01-01           1894        380
7  ang mo kio town centre 2020-01-01           1200        176
8                   anson 2020-01-01            265         77
9               balestier 2020-01-01           3543       1289

In [17]:
(
    df
    .groupby("subzone")[["android_count", "ios_count"]]
    .sum()
    .assign(ios_android_ratio=lambda df_: df_["ios_count"] / df_["android_count"])
    .sort_values(["ios_android_ratio"], ascending=False)
)

                               android_count  ios_count  ios_android_ratio
subzone
pulau punggol timor                        1          2           2.000000
pulau punggol barat                        8          8           1.000000
istana negara                          82996      56797           0.684334
holland road                          134189      80735           0.601651
somerset                              134044      77879           0.580996
kovan                                 574231     280308           0.488145
tiong bahru                           126356      61290           0.485058
coronation road                        66740      31523           0.472325
upper thomson                         353564     150373           0.425306
joo seng                              164678      64788           0.393422
serangoon garden                      475476     182849           0.384560
woodleigh                             112895      42542           0.376828
anak bukit                            137242      51703           0.376729
lorong ah soo                         463472     174071           0.375580
jelebu                                200123      74726           0.373400
punggol canal                           4683       1705           0.364083
kembangan                             216379      77155           0.356573
mei chin                               75423      26533           0.351789
oxley                                  14698       5152           0.350524
paterson                               23143       8072           0.348788
hillview                               52341      18236           0.348408
frankel                               187467      64981           0.346626
robertson quay                         58539      20090           0.343190
newton circus                          25344       8664           0.341856
fernvale                              265978      89210           0.335404
balestier                             335906     112641           0.335335
geylang east                          305011     101440           0.332578
yishun central                         73667      24432           0.331655
clementi central                      105286      34843           0.330937
boulevard                             103750      34271           0.330323
pasir ris central                     115021      37958           0.330009
bras basah                             38796      12779           0.329390
chatsworth                             95196      31315           0.328953
mountbatten                            61629      20214           0.327995
choa chu kang central                 156183      51095           0.327148
dhoby ghaut                            45787      14958           0.326687
greenwood park                          1740        560           0.321839
bugis                                  83301      26652           0.319948
seletar hills                         121947      38990           0.319729
yunnan                                336417     106678           0.317101
woodlands west                        153862      48584           0.315763
sennett                                67419      20937           0.310550
anson                                  26803       8261           0.308212
pasir panjang 1                        38389      11830           0.308161
katong                                 65182      19864           0.304747
dover                                  53848      16345           0.303540
tyersall                               49781      15041           0.302143
punggol field                         124972      37652           0.301283
mount emily                            33545       9984           0.297630
pasir ris west                         85069      25087           0.294902
malcolm                                28683       8383           0.292264
tampines east                         472077     137340           0.290927
ulu pandan                             34591      10048           0.290480
hougang central                        54394      15745           0.289462
leonie hill                            32883       9472           0.288052
flora drive                            52796      15164           0.287219
marymount                             108795      31213           0.286897
institution hill                       27618       7919           0.286733
farrer court                           27594       7912           0.286729
margaret drive                         61535      17491           0.284245
tanjong pagar                          39686      11227           0.282896
sengkang town centre                  189420      53194           0.280826
central subzone                        61553      17240           0.280084
kangkar                                95013      26437           0.278246
tiong bahru station                    74997      20866           0.278224
one tree hill                          25124       6989           0.278180
moulmein                              114646      31839           0.277716
tanglin                                23167       6403           0.276385
simei                                 166568      45786           0.274879
phillip                                16874       4625           0.274090
bencoolen                              57225      15650           0.273482
yio chu kang east                      49086      13389           0.272766
commonwealth                           26434       7153           0.270598
tampines west                         253719      68532           0.270110
marine parade                         131038      35366           0.269891
trafalgar                             146879      39629           0.269807
clementi woods                         65596      17594           0.268218
townsville                             69198      18405           0.265976
alexandra north                        29602       7866           0.265725
holland drive                          45750      12127           0.265071
telok blangah rise                     41474      10978           0.264696
lakeside                               85243      22535           0.264362
victoria                               61705      16277           0.263787
rochor canal                           33273       8771           0.263607
bedok reservoir                        87614      22914           0.261534
dunearn                                36279       9473           0.261115
punggol town centre                    21398       5561           0.259884
kampong glam                           40764      10580           0.259543
henderson hill                         77481      20089           0.259276
serangoon central                     138560      35678           0.257491
bukit batok central                    86263      22035           0.255440
national university of s pore          68203      17328           0.254065
toh guan                               67140      17010           0.253351
clementi north                        105741      26788           0.253336
siglap                                 35061       8840           0.252132
everton park                           50344      12674           0.251748
telok blangah way                      46812      11755           0.251111
shangri-la                             52748      13233           0.250872
kampong ubi                           188445      47192           0.250429
ghim moh                               39044       9764           0.250077
chinatown                             103617      25836           0.249341
raffles place                          68551      17034           0.248487
bukit batok west                       57303      14232           0.248364
cheng san                             108486      26858           0.247571
bendemeer                             155963      38458           0.246584
kebun bahru                            72090      17775           0.246567
toa payoh west                         65765      16188           0.246149
bayshore                               30631       7500           0.244850
china square                           43314      10586           0.244401
hougang east                           77678      18975           0.244278
serangoon north                        86535      21101           0.243844
queensway                              21940       5341           0.243437
one north                             123274      29902           0.242565
yio chu kang                           55721      13511           0.242476
pasir ris drive                       176733      42824           0.242309
leedon park                            52534      12724           0.242205
alexandra hill                         88130      21327           0.241995
cairnhill                              38304       9230           0.240967
depot road                             38220       9202           0.240764
bedok south                           141779      34020           0.239951
boon teck                              54804      13129           0.239563
yishun south                          123831      29531           0.238478
yuhua east                             99525      23617           0.237297
toa payoh central                     139129      32944           0.236787
clarke quay                            36388       8591           0.236094
mandai estate                           7823       1845           0.235843
taman jurong                          172656      40601           0.235155
redhill                                58505      13718           0.234476
international business park            25847       6018           0.232832
chong boon                            105946      24517           0.231410
hong kah north                         84784      19606           0.231246
tanjong rhu                            70505      16265           0.230693
khatib                                 63520      14504           0.228338
changi airport                        183453      41886           0.228320
matilda                               122967      28059           0.228183
yio chu kang west                      63115      14374           0.227743
jurong west central                   188570      42881           0.227401
anchorvale                            130767      29707           0.227175
singapore polytechnic                  54126      12249           0.226305
swiss club                             53956      12203           0.226166
yuhua west                             71147      16040           0.225449
rivervale                             189513      42673           0.225172
pasir panjang 2                        54778      12191           0.222553
clementi west                          64573      14347           0.222183
singapore general hospital             53944      11959           0.221693
hougang west                          191138      42322           0.221421
telok blangah drive                    89696      19784           0.220567
bukit ho swee                          63460      13983           0.220344
faber                                  26338       5793           0.219948
nassim                                 82473      18129           0.219817
bedok north                           312353      68531           0.219402
guilin                                 68535      15034           0.219362
pei chun                               31298       6859           0.219151
bukit merah                            47520      10374           0.218308
macpherson                            122678      26671           0.217407
peng siang                             72112      15561           0.215789
bishan east                           142177      30544           0.214831
bangkit                                68957      14747           0.213858
hillcrest                              48111      10288           0.213839
bidadari                               33801       7207           0.213219
saujana                                63257      13466           0.212878
dairy farm                             35761       7556           0.211292
tuas promenade                           256         54           0.210938
aljunied                              349524      73447           0.210134
geylang bahru                          66210      13757           0.207778
goodwood park                          13930       2883           0.206963
jurong gateway                        124544      25701           0.206361
boon lay place                        102346      21109           0.206251
sembawang springs                      34241       7056           0.206069
nature reserve                         38324       7896           0.206033
keat hong                              92182      18818           0.204140
gombak                                 81422      16557           0.203348
crawford                               82825      16838           0.203296
orange grove                           15966       3233           0.202493
upper paya lebar                       90708      18292           0.201658
kallang bahru                         123757      24876           0.201007
serangoon north ind estate             45530       9135           0.200637
fajar                                  60772      12148           0.199895
waterway east                          63550      12699           0.199827
teck whye                              73632      14602           0.198311
pasir ris wafer fab park               24777       4896           0.197603
lorong 8 toa payoh                     38368       7563           0.197117
yew tee                                80944      15895           0.196370
hong kah                              204792      39998           0.195310
braddell                               40660       7879           0.193778
springleaf                             24494       4737           0.193394
kampong java                          120885      23358           0.193225
tai seng                              113469      21924           0.193216
selegie                                19271       3714           0.192725
midview                                80582      15473           0.192016
bukit batok east                       56256      10773           0.191500
admiralty                               3877        741           0.191127
kallang way                            49567       9439           0.190429
peoples park                           41890       7846           0.187300
changi west                            46667       8711           0.186663
yishun west                           231439      43185           0.186593
lorong chuan                           53972      10065           0.186486
compassvale                           106990      19838           0.185419
kent ridge                             28596       5301           0.185376
tanglin halt                           65721      12123           0.184462
mount pleasant                         41356       7590           0.183528
coney island                            2774        507           0.182769
monks hill                             15603       2846           0.182401
sembawang hills                        33433       6071           0.181587
kim keat                               31058       5611           0.180662
woodgrove                              99184      17810           0.179565
bukit batok south                     105756      18867           0.178401
ang mo kio town centre                 81121      14391           0.177402
woodlands east                        215195      37950           0.176352
tagore                                 62715      11054           0.176258
simpang north                           1872        326           0.174145
sembawang east                          5801       1006           0.173418
choa chu kang north                    87142      15111           0.173407
seletar aerospace park                 19891       3446           0.173244
sunset way                             28240       4884           0.172946
senoko south                            8363       1446           0.172904
simpang south                           6474       1112           0.171764
loyang east                            20955       3573           0.170508
woodlands south                       115865      19705           0.170069
city terminals                         46391       7847           0.169149
yishun east                           126637      21401           0.168995
sembawang central                      34770       5740           0.165085
lower seletar                          90785      14827           0.163320
xilin                                 103062      16830           0.163300
kampong bugis                          48810       7940           0.162672
yio chu kang north                     18188       2918           0.160435
marina east                             9211       1460           0.158506
teban gardens                          99016      15662           0.158176
marina east mp                         10196       1599           0.156826
ridout                                 37700       5878           0.155915
sungei road                            42098       6501           0.154425
seletar                                30003       4608           0.153585
marina centre                         283870      43473           0.153144
senja                                  76136      11642           0.152911
fort canning                           59267       9011           0.152041
woodlands regional centre              80136      12180           0.151992
airport road                            7568       1149           0.151823
boon keng                              63485       9597           0.151170
west coast                             41157       6208           0.150837
northland                             116436      17401           0.149447
potong pasir                           68684      10221           0.148812
brickworks                             79583      11786           0.148097
tampines north                         78492      11609           0.147900
lavender                              179966      26408           0.146739
kampong tiong bahru                    68035       9879           0.145205
kaki bukit                            251009      36239           0.144373
mackenzie                              13109       1889           0.144099
wenya                                  72633      10348           0.142470
chin bee                               33138       4587           0.138421
loyang west                            54651       7555           0.138241
defu industrial park                   68472       9378           0.136961
sengkang west                          15383       2103           0.136709
lorong halus north                      5396        716           0.132691
port                                   56818       7369           0.129695
farrer park                            97050      12511           0.128913
little india                          107696      13543           0.125752
marina south                           26918       3369           0.125158
nee soon                               23149       2636           0.113871
east coast                             20596       2338           0.113517
paya lebar east                        16750       1831           0.109313
paya lebar west                        15190       1635           0.107637
plab                                   25331       2661           0.105049
penjuru crescent                       33812       3506           0.103691
paya lebar north                       36464       3744           0.102677
tukang                                 43146       4284           0.099291

In [ ]:
df.to_csv(SAVEPATH, index=False)