In [8]:
# huh NEA?
import os
import geopandas as gpd
import pandas as pd
pd.set_option('display.max_columns', 100)

from utilities import get_html_table_metadata

import warnings
warnings.filterwarnings('ignore')

In [19]:
FP_HAWKERS = os.path.join("raw-data", "HawkerCentresGEOJSON.geojson")

gdf_hawkers = (
    gpd.read_file(FP_HAWKERS)
    .pipe(get_html_table_metadata)
)
hawkers1_name = gdf_hawkers["NAME"]
hawkers1_pc = gdf_hawkers["ADDRESSPOSTALCODE"]
gdf_hawkers

,Name,Description,geometry,AWARDED_DATE,LANDYADDRESSPOINT,PHOTOURL,ADDRESSBLOCKHOUSENUMBER,DESCRIPTION,EST_ORIGINAL_COMPLETION_DATE,STATUS,APPROXIMATE_GFA,INFO_ON_CO_LOCATORS,NAME,ADDRESSBUILDINGNAME,HUP_COMPLETION_DATE,LANDXADDRESSPOINT,ADDRESSSTREETNAME,ADDRESSPOSTALCODE,IMPLEMENTATION_DATE,ADDRESS_MYENV,INC_CRC,FMEL_UPD_D
0,kml_1,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.85016 1.28442 0),17/7/2017,29650.7,NaN,50,New Replacement Centre,15/11/2021,Existing (replacement),NaN,hawker centre/commercial space,Market Street Hawker Centre,CapitaSpring,NaN,29874.82,Market Street,48940,1/8/2017,NaN,DB83871D0E006559,20221017143612
1,kml_2,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.77978 1.43354 0),4/9/2015,46139.03,http://www.nea.gov.sg/images/default-source/Ha...,4,New Replacement Centre,8/11/2017,Existing (replacement),3661,hawker centre/supermarket/shops,Marsiling Mall Hawker Centre,Marsiling Mall,NaN,22042.51,Woodlands Street 12,738623,1/1/2016,"Blk 4,Woodlands St 12,Singapore�738623",67D9A36B865FC1FB,20221017143612
2,kml_3,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.80472 1.29749 0),11/5/2015,31094.91,NaN,38A,New Replacement Centre,30/3/2022,Existing (replacement),NaN,hawker centre/branch office/supermarket/shops/...,Margaret Drive Hawker Centre,NaN,NaN,24816.7,Margaret Drive,142038,2/12/2015,NaN,C80F89698B7A8757,20221017143612
3,kml_4,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.87706 1.39159 0),30/7/2018,41500.77,NaN,21,New Centre,22/3/2022,Existing (new),NaN,hawker centre/market/community club,Fernvale Hawker Centre & Market,"Fernvale Community Club, Hawker Centre & Market",NaN,32867.9,Sengkang West Avenue,797650,13/8/2018,NaN,E3AB7D1743979E42,20221017143612
4,kml_5,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.90481 1.40819 0),8/8/2018,43336.13,NaN,1,New Centre,29/4/2022,Existing (new),NaN,hawker centre/Regional Library/Senior Care Cen...,One Punggol Hawker Centre,One Punggol,NaN,35955.52,Punggol Drive,828629,29/8/2018,NaN,4780858D968F79C9,20221017143612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,kml_121,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.75975 1.3118 0),NaN,32678.15,http://www.nea.gov.sg/images/default-source/Ha...,503,HUP Standard Upgrading,26/3/1979,Existing,NaN,NaN,West Coast Drive Blk 503 (Ayer Rajah Food Centre),NaN,15/12/2002,19812.66,West Coast Drive,120503,NaN,"Blk 503, West Coast Drive, Singapore 120503",7A27983404FB5BA2,20221012163049
121,kml_122,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.85514 1.32294 0),NaN,33909.85,http://www.nea.gov.sg/images/default-source/Ha...,90,HUP Standard Upgrading,26/8/1976,Existing,NaN,NaN,Whampoa Drive Blk 90 (Whampoa Drive Makan Plac...,NaN,25/10/2007,30428.25,Whampoa Drive,320090,NaN,"Blk 90, Whampoa Drive, Singapore 320090",16F08FA02D2A5DE5,20221012163049
122,kml_123,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.85407 1.32342 0),NaN,33962.78,http://www.nea.gov.sg/images/default-source/Ha...,91/92,HUP Standard Upgrading,3/1/1973,Existing,NaN,NaN,Whampoa Drive Blk 91/92 (Whampoa Drive Makan P...,NaN,25/10/2007,30309.21,Whampoa Drive,320091,NaN,"Blk 91/92, Whampoa Drive, Singapore 320091/320092",38A4F531F9CF7A4C,20221012163049
123,kml_124,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.84475 1.42502 0),23/10/2015,45196.73,http://www.nea.gov.sg/images/default-source/Ha...,51,New Centre,3/7/2017,Existing (new),3364,NaN,Yishun Park Hawker Centre,Yishun Park Hawker Centre,NaN,29271.88,Yishun Avenue 11,768867,25/11/2015,"Blk 51, Yishun Avenue 11, Singapore 768867",2676B659B081726B,20221012163049
124,kml_125,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.82854 1.43145 0),NaN,45907.73,http://www.nea.gov.sg/images/default-source/Ha...,104/105,HUP Standard Upgrading,31/3/1984,Existing,NaN,NaN,Yishun Ring Road Blk 104/105 (Chong Pang Marke...,NaN,4/8/2003,27467.95,Yishun Ring Road,760104,NaN,"Blk 104/105, Yishun Ring Road, Singapore 76010...",A75CB1D5E4C5BBE2,20221012163049

,Name,Description,geometry,AWARDED_DATE,LANDYADDRESSPOINT,PHOTOURL,ADDRESSBLOCKHOUSENUMBER,DESCRIPTION,EST_ORIGINAL_COMPLETION_DATE,STATUS,APPROXIMATE_GFA,INFO_ON_CO_LOCATORS,NAME,ADDRESSBUILDINGNAME,HUP_COMPLETION_DATE,LANDXADDRESSPOINT,ADDRESSSTREETNAME,ADDRESSPOSTALCODE,IMPLEMENTATION_DATE,ADDRESS_MYENV,INC_CRC,FMEL_UPD_D
81,kml_82,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.82601 1.28 0),NaN,29161.95,http://www.nea.gov.sg/images/default-source/Ha...,112,HUP Standard Upgrading,1/1/1969,Existing,NaN,NaN,Jalan Bukit Merah Blk 112 (Blk 112 Jalan Bukit...,NaN,28/11/2013,27186.98,Jalan Bukit Merah,160112,NaN,"Blk 112, Jalan Bukit Merah, Singapore 160112",F6CA40B9C1F55859,20221012163049
105,kml_106,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.8184 1.28786 0),NaN,30030.33,http://www.nea.gov.sg/images/default-source/Ha...,79,HUP Reconfiguration,1/1/1969,Existing,NaN,NaN,Redhill Lane Blk 79 (Redhill Market),NaN,28/6/2005,26339.98,Redhill Lane,150079,NaN,"Blk 79, Redhill Lane, Singapore 150079",ECAC58C7BB3929B3,20221012163049

In [21]:
FP_HAWKERS2 = os.path.join("raw-data", "NEAMarketandFoodCentre.geojson")
gdf_hawkers2 = (
    gpd.read_file(FP_HAWKERS2)
    .pipe(get_html_table_metadata)
)
hawkers2_name = gdf_hawkers2["NAME_OF_CENTRE"]
hawkers2_pc = gdf_hawkers2["POSTAL_CODE"]
gdf_hawkers2

,Name,Description,geometry,TOTAL_STALLS,MP_STALLS,CF_STALLS,POSTAL_CODE,OWNER,TYPE,LOCATION_CENTRE,NAME_OF_CENTRE,INC_CRC,FMEL_UPD_D
0,kml_1,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.85296 1.33602 0),36,0,36,310075,HDB,HC,"Blk 75, Lorong 5 Toa Payoh, S(310075)",Blk 75 Toa Payoh Lorong 5,28804B15B61FFD38,20141226094235
1,kml_2,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.81833 1.28778 0),122,122,0,150079,HDB,MK,"Blk 79, Redhill Lane, S(150079)",Blk 79 Redhill Lane,37110F2F3881254A,20141226094235
2,kml_3,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.80762 1.27336 0),40,0,40,100079,HDB,HC,"Blk 79, Telok Blangah Drive, S(100079)",Blk 79 Telok Blangah Drive,03DDF269AFE14015,20141226094235
3,kml_4,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.8871 1.32783 0),59,43,16,370080,HDB,MHC,"Blk 80, Circuit Road, S(370080)",Blk 80 Circuit Road,7D1CFE1B31C61F53,20141226094235
4,kml_5,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.8079 1.27389 0),64,64,0,100082,HDB,MK,"Blk 82, Telok Blangah Drive, S(100082)",Blk 82 Telok Blangah Drive,76ABA9C1D2A8E8F6,20141226094235
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,kml_106,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.87001 1.32146 0),211,127,84,330069,HDB,MHC,"Blk 69, Geylang Bahru, S(330069)",Blk 69 Geylang Bahru,870C4347BE39F0BC,20141226094235
106,kml_107,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.80564 1.31625 0),108,68,40,260007,HDB,MHC,"Blk 7, Empress Road, S(260007)",Blk 7 Empress Road,D718436C85F3AAA0,20141226094235
107,kml_108,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.84651 1.37217 0),123,78,45,560724,HDB,MHC,"Blk 724, Ang Mo Kio Ave 6, S(560724)",Blk 724 Ang Mo Kio Ave 6,93616A592D1E269C,20141226094235
108,kml_109,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.76425 1.30381 0),195,135,60,120726,HDB,MHC,"Blk 726, Clementi West Street 2, S(120726)",Blk 726 Clementi West Street 2,6712BAB9FB414D33,20141226094235
109,kml_110,<center><table><tr><th colspan='2' align='cent...,POINT Z (103.852 1.33455 0),90,80,10,310074,HDB,MHC,"Blk 74, Lorong 4 Toa Payoh, S(310074)",Blk 74 Toa Payoh Lorong 4,70A8297B95D563DA,20141226094235

In [29]:
hawkers1_name = [x.lower() for x in hawkers1_name]
hawkers2_name = [x.lower() for x in hawkers2_name]
overlap = list(set(hawkers1_name) & set(hawkers2_name))
print(overlap)
print(len(overlap))

['geylang serai market', 'tiong bahru market', 'newton food centre', 'chomp chomp food centre', 'beo crescent market', 'east coast lagoon food village', 'serangoon garden market', 'adam road food centre', 'bukit timah market', 'tanglin halt market', 'dunman food centre', 'zion riverside food centre', 'commonwealth crescent market', 'berseh food centre', 'bedok food centre', 'golden mile food centre', 'pasir panjang food centre']
17

In [30]:
ix = 0
for h in hawkers1_name:
    if h in hawkers2_name:
        print(h)
        ix +=1
ix

adam road food centre
bedok food centre
beo crescent market
berseh food centre
bukit timah market
chomp chomp food centre
commonwealth crescent market
dunman food centre
east coast lagoon food village
geylang serai market
golden mile food centre
tanglin halt market
zion riverside food centre
newton food centre
pasir panjang food centre
serangoon garden market
tiong bahru market

17

In [31]:
ix = 0
for h in hawkers2_name:
    if h in hawkers1_name:
        print(h)
        ix += 1
ix

commonwealth crescent market
adam road food centre
serangoon garden market
tanglin halt market
tiong bahru market
zion riverside food centre
bedok food centre
beo crescent market
berseh food centre
bukit timah market
chomp chomp food centre
dunman food centre
east coast lagoon food village
geylang serai market
golden mile food centre
newton food centre
pasir panjang food centre

17

### postal code overlap

In [47]:
hawkers1_pc_clean = [str(x).strip().lower() for x in hawkers1_pc]
hawkers2_pc_clean = [str(x).strip().lower() for x in hawkers2_pc]
overlap = list(set(hawkers1_pc) & set(hawkers2_pc))
print(overlap)
print(len(overlap))

['588215', '208877', '441050', '564226', '560724', '277700', '560409', '530105', '149644', '50032', '430013', '151115', '150085', '557269', '320090', '150120', '150163', '118543', '380017', '370079', '424768', '600254', '574419', '641221', '560341', '760104', '120502', '560160', '120503', '402004', '601037', '310127', '570320', '370080', '69111', '198783', '260007', '211041', '380049', '320091', '555945', '460538', '460085', '402001', '180270', '310022', '199583', '730020', '568226', '150079', '460216', '247792', '470630', '229495', '468960', '462208', '330069', '460511', '90036', '120353', '310074', '560628', '469572', '141001', '310093', '140159', '530209', '600347', '81006', '560527', '289876', '370089', '380117', '50335', '310210', '397972', '618499', '90011', '270044', '270020', '390051', '161022', '440084', '330029', '69184', '210665', '161001', '432004', '48940', '51531', '150006', '100079', '148813', '168898', '500002', '120448', '640505', '461058', '169982', '100082', '120726', '561453', '310075', '460016', '521137', '160112']
106

In [52]:
ix = 0
for h in hawkers1_pc_clean:
    if h not in hawkers2_pc_clean:
        print(h)
        ix += 1
print(ix)

738623
142038
797650
828629
756973
677632
544692
651469
103078
679947
538776
528523
363202
540339
nan
648202
730676
519641
768867
19

In [53]:
ix = 0
for h in hawkers2_pc_clean:
    if h not in hawkers1_pc_clean:
        print(h)
        ix += 1
print(ix)

618824
139957
139956
731004
4